name: build-and-deploy
run-name: Build-And-Deploy

on: 
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ github.actor }}! You just triggered a build."

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish
        run: dotnet publish -c Release --no-restore

      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./output/Release/net9.0/publish

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build-output

      - name: Azure Auth
        uses: azure/login@v1
        with:
          creds: '{
            "tenantId": "${{ vars.AZURE_TENANT_ID }}",
            "subscriptionId":"${{ vars.AZURE_SUBSCRIPTION_ID }}",
            "clientId": "${{ vars.AZURE_CLIENT_ID }}",
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}"
          }'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.IDENTITY_AZURE_WEB_NAME }}
          publish-profile: ${{ secrets.IDENTITY_AZURE_WEB_PROFILE }}
          package: ./build-output

#      - name: Azure App Service Settings
#        uses: Azure/appservice-settings@v1
#        with:
#          app-name: ${{ vars.IDENTITY_AZURE_WEB_NAME_FULL }}
#          app-settings-json: '[
#            {
#              "name": "ConnectionStrings:DefaultConnection",
#              "value": "${{ secrets.IDENTITY_SQL_CONNECTION_STRING }}",
#              "slotSetting": false
#            }
#          ]'
#          mask-inputs: true