name: deploy-to-azure
run-name: Deploy to Azure

on:
  workflow_run:
    workflows: 
      - "Build"
    types:
      - completed

jobs:

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build-output

      - name: List files
        run: ls -R .

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.IDENTITY_AZURE_WEB_NAME }}
          publish-profile: ${{ secrets.IDENTITY_AZURE_WEB_PROFILE }}
          package: ./build-output